version: "2"

# define HOSTNAME before launching compose!

services:
    elmer:
        tty: true
        image: us.gcr.io/gcpdrive-sjstest/elmer-eg:1
        platform: linux/amd64
        volumes:
            - ${PWD}:/home
        environment:
            - DISPLAY=$HOSTNAME:0
        command:
            - ElmerGUI

